### ISSUE TITLE
A possibly better the __dict__ variable?

### ISSUE THREAD

**Issue by liuzheng1990** [EliFinkelshteyn/alphabet-detector#10]
Hi, thanks for designing this small useful alphabet detecting package. It works good enough for me, but I noticed the `ad.__dict__` instance variable. The body of this dictionary is basically of the form:

```
{'LATIN': {'ε': False, 'm': True, 'e': True, 'a': True, 'n': True, 's': True, 'g': True, 'r': True}}
```

Would it be more efficient if we store it like the following:

```
{'LATIN': {'m', 'g', 'k', 'e'}, 'GREEK': {'ε', 'λ', 'ά'}, 'CJK': {'你', '好'}}
```

I know it took its current structure because you wrapped up the discussion in a StackExchange thread, but I think as the number of queries increases, the former dictionary will be very memory consuming, while the latter should save memory and also be efficient in time?

Hope to have more discussion!

**Comment by EliFinkelshteyn** [comment]
Hey @liuzheng1990, thanks for the comment and for using the library. Your suggestion is interesting, but it wouldn't keep memory of false matches, only true matches. Because of that, we'd need to always go back to check against `unicodedata` for any letter not in an alphabet, which would be relatively slower. 

About memory: since there are only [109,384 total assigned unicode characters](http://www.unicode.org/versions/Unicode6.0.0/ch01.pdf), the vast majority of which are very rare, you'd have to have a really unique use case to have memory be an issue. 

All of that said, I'm certainly open to being proven wrong and collaborating. Any interest in running benchmarks against something like your idea to see if it pans out? If it does, I'd be happy to merge a PR.

**Comment by liuzheng1990** [comment]
@EliFinkelshteyn Great answer! My concern was that every character would probably appear in many dicts, once in 'LATIN', once in 'CJK', once in 'GREEK', etc. Only one of these appearance is a True and all others are False. But you are right, even these may not consume a considerable amount of memory.

Yeah. Actually I'm only using it on very lightweight tasks. I'll keep an eye on this performance and initiate another discussion if I find notable problems. For now, thanks very much for your answer!
